// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModlistManager.Data;

#nullable disable

namespace ModlistManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ModlistManager.Data.Entities.AdminCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminCredentials");
                });

            modelBuilder.Entity("ModlistManager.Data.Entities.ModRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FetchLog")
                        .HasColumnType("TEXT");

                    b.Property<string>("FetchStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkshopId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkshopUrlInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Game");

                    b.HasIndex("RequesterName");

                    b.HasIndex("Status");

                    b.ToTable("ModRequests");
                });

            modelBuilder.Entity("ModlistManager.Data.Entities.ModRequestModId", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModRequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModRequestId");

                    b.ToTable("ModRequestModIds");
                });

            modelBuilder.Entity("ModlistManager.Data.Entities.ModRequestModId", b =>
                {
                    b.HasOne("ModlistManager.Data.Entities.ModRequest", "ModRequest")
                        .WithMany("ModIds")
                        .HasForeignKey("ModRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModRequest");
                });

            modelBuilder.Entity("ModlistManager.Data.Entities.ModRequest", b =>
                {
                    b.Navigation("ModIds");
                });
#pragma warning restore 612, 618
        }
    }
}
